import { ColorSchemeScript } from "@mantine/core";
import type { Metadata } from "next";
import HeaderComponent from "../ui/Header";
import FooterComponent from "../ui/Footer";
import NextAuthSessionProvider from "../ui/provider/NextAuthSessionProvider";
import MantineThemeProvider from "../ui/provider/MantineThemeProvider";
import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";

export const metadata: Metadata = {
  title: "GLOBAL",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <NextAuthSessionProvider>
          <MantineThemeProvider>
            <div className="flex flex-col min-h-screen">
              <HeaderComponent />
              <div className="max-w-[1800px] w-full flex-1 flex-col self-center">
                {children}
              </div>
              <FooterComponent />
              {modal}
            </div>
          </MantineThemeProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
