import type { Metadata } from "next";
import "@mantine/core/styles.css";
import { NavbarMenu } from "@/app/ui/navbar/NavbarMenu";

export const metadata: Metadata = {
  title: "GLOBAL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="grid grid-cols-[200px_1fr]">
      <NavbarMenu />
      <div className="flex flex-col flex-grow px-xl py-md">{children}</div>
    </div>
  );
}
